###

GET  http://localhost:3000/tables HTTP/1.1

###

POST http://localhost:3000/tables HTTP/1.1
content-type: application/json

{
    "capacity": 2
}

###

GET  http://localhost:3000/guest_list HTTP/1.1

###

POST http://localhost:3000/guest_list/danica HTTP/1.1
content-type: application/json

{
    "table": 1,
    "accompanying_guests": 1
}

###

GET http://localhost:3000/guests

###

PUT http://localhost:3000/guests/amaury HTTP/1.1
content-type: application/json

{
    "accompanying_guests": 1
}

###

DELETE http://localhost:3000/guests/amaury

###

PUT http://localhost:3000/guests/name HTTP/1.1
content-type: application/json

{
    "accompanying_guests": 0
}

###

GET http://localhost:3000/seats_empty
